version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ci_db
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../aplication:/var/www/html
    depends_on:
      - db

